Abort pre-commit script when no files are changed
Running this script when there are no files to stash
will mess up the current files and pop previous
stashes from the stash list.

Exit early to avoid the mess: it makes little sense to do a
linting of changed files when there are none, so it should
be seen as a mistake anyway.

diff --git a/scripts/eslint-pre-commit b/scripts/eslint-pre-commit
--- a/scripts/eslint-pre-commit
+++ b/scripts/eslint-pre-commit
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if git status -uno --porcelain | wc -l | egrep ' +0' > /dev/null; then
+    echo "No files to commit. Aborting pre-commit check"
+    exit 1
+fi
+
 git stash -q --keep-index
 
 # Test prospective commit
